name: Docker Build and Run

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker containers
        run: docker compose build

      - name: Run Docker containers
        run: docker compose up -d

      - name: Check running containers
        run: docker compose ps

      - name: Check application logs
        run: docker compose logs --tail=50
